config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'devise_registrations', :sessions => 'devise_sessions' }
  get "/profile/:id" => "users#profile", as: :user_profile
  post "/profile/:id" => "users#attack"

  root 'main#index'

  get "/base"                 => "base#index"
  get "/base/create"          => "base#create"
  get "/base/info"            => "base#info"
  
  get "/user/resources"       => "base#resources"

  get "/base/building/info"   => "building#info"
  get "/base/building/create" => "building#create"
  get "/base/building/update" => "building#update"
  get "/base/building/cost"   => "building#cost"

  get "/base/entity/info"     => "entity#info"
  get "/base/entity/add"      => "entity#add"
  get "/base/entity/remove"   => "entity#remove"
  get "/base/entity/cost"     => "entity#cost"

  get "/rank" => "rank#rank"

  get "/battles" => "battle#index"
  get "/battles/:name" => "battle#show"

  get "/simulator" => "combat_simulator#simulator"
  post "/simulator/" => "combat_simulator#run"

end

app/controllers/rank_controller.rb
class RankController < ApplicationController
	before_action :authenticate_user!

	def rank
		# FIXME: no defined order. Decide and implement an order
		# FIXME: don't show all users, only the nearest ones
		@profile_id = current_user.id
		@ranks = UserRank.order('total_level DESC')

		if mobile_device?
      render :mobile, layout: "mobile"
    else
      render :desktop, layout: "desktop"
    end
	end
end

app/helpers/rank_helper.rb
module RankHelper
end

app/views/rank/desktop.html.erb
<div class="ranking_table row padding-top margin-top">
    <% @ranks.each_with_index do |an_user_rank, index| %>
      <div class="ranking_row column_8 offset_2 bck grey margin-bottom padding-top padding-bottom">
        <h5 class="inline text bold color theme margin-left"><%= index + 1 %>. <%= link_to(an_user_rank.user.name, user_profile_path(an_user_rank.user)) %></h5>
        <% if an_user_rank.user.admin %>
        	<span class='tag bck red'>ADMIN</span>
        <% end %>
        <h6 class="inline text bold right color dark on-right padding-right"><%= an_user_rank.total_level %></h6>
      </div>
    <% end %>
</div>